### ISSUE TITLE
moin, bei mehr als 149 möglichen Items in Loxone stürzt Homebridge ab und startet neu bis man das plugin wieder deaktiviert

### ISSUE THREAD

**Issue by TommeDE** [rudyberends/homebridge-loxone-proxy#1]
[28/04/2023, 02:07:26] [LoxonePlatform] [mapLoxoneItems] Found item: [Schlafzimmer] Grün with type MoodSwitch
[28/04/2023, 02:07:26] [LoxonePlatform] [LoxoneAccesory] Adding new accessory: [Schlafzimmer] Grün
[28/04/2023, 02:07:26] Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory.addBridgedAccessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:13)
    at Bridge.Accessory.addBridgedAccessories (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:707:12)
    at BridgeService.handleRegisterPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.registerPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/api.ts:340:10)
    at new LoxoneAccessory (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:75:25)
    at LoxonePlatform.mapLoxoneItems (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:151:7)
    at LoxonePlatform.parseLoxoneConfig (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:67:10)
    at LoxonePlatform.LoxoneInit (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:37:12)
ERROR: Socket Timeout fired! (timeout was 5ms)
[28/04/2023, 02:07:26] [LoxonePlatform] Socket closed 2004
[28/04/2023, 02:07:26] [LoxonePlatform] Reconnecting in 10 seconds...

**Comment by rudyberends** [comment]
Danke für die Rückmeldung. Ich habe das Plugin für den persönlichen Gebrauch erstellt und es wurde nie mit anderen Loxone-Umgebungen außer meiner eigenen getestet. Es gibt also wahrscheinlich noch mehr Fehler, auf die ich selbst nicht gestoßen bin. Aber wenn sie hier gemeldet werden, können wir immer sehen, ob wir sie lösen können.

Das Limit von 150 items ist ein HomeKit-Limit. Apple erlaubt nicht mehr als 150 items pro Bridge.

Ich habe eine Anpassung im Plugin vorgenommen, die jetzt die Zuordnung von Elementen stopt, wenn das Limit erreicht ist. Sind aber auch andere Plugins aktiv, dann kann das Limit trotzdem überschritten werden. Um dies zu verhindern, kann das Plugin als Child Bridge gestartet werden.

Ich habe auch eine Option hinzugefügt, um die Verwendung von MoodSwitches zu deaktivieren, wenn Sie sie nicht verwenden möchten. Auch das spart einiges an Items ein und bleibt so unter Umständen unter dem Limit.

Könnten Sie die neueste Version des Plugins testen, um zu sehen, ob es für Sie funktioniert? Sie müssen wahrscheinlich das zwischengespeicherte Zubehör in Homebridge leeren.

**Comment by TommeDE** [comment]
ich schaue gleich mal und wir können gern beim du bleiben ;)

**Comment by TommeDE** [comment]
mit dem switch habe ich weniger als 150 das läuft und ohne kommt gleich

**Comment by TommeDE** [comment]
weiterhin als child aber schmiert ab ... da steht 149 vielleicht liegt es daran?

[28/04/2023, 19:06:53] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Lila
Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:707:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:340:10)
    at new LoxoneAccessory (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:54:25)
    at LoxonePlatform.mapLoxoneItems (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:180:9)
    at LoxonePlatform.parseLoxoneConfig (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:85:10)
    at LoxonePlatform.LoxoneInit (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:56:10)
[28/04/2023, 19:06:53] [homebridge-loxone-proxy] Child bridge process ended

**Comment by rudyberends** [comment]
Hast du die Homebridge "Cached Accessories" gelöscht? Wenn Sie die neueste Version verwenden, sollte das Plugin so aussehen, wenn es sein Limit erreicht;

`
_[4/28/2023, 4:17:25 PM] [LoxonePlatform] [mapLoxoneItems][Item 148] Found item: [Woonkeuken] Autopilot with type MoodSwitch
[4/28/2023, 4:17:25 PM] [LoxonePlatform] [LoxoneAccesory] Adding new accessory: [Woonkeuken] AutoPilot
[4/28/2023, 4:17:25 PM] [LoxonePlatform] [mapLoxoneitems] Maximum number of supported HomeKit items reached. Stop mapping Items._`

**Comment by TommeDE** [comment]
öhm ich hab die homebridge neu gestartet sonst weiß ich nicht wie

**Comment by TommeDE** [comment]
eigentlich endet das schon bei 110 wie es aussieht ... 

`[28/04/2023, 19:33:54] [homebridge-loxone-proxy] [mapLoxoneItems][Item 109] Found item: [Keller] Lila with type MoodSwitch
[28/04/2023, 19:33:54] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Lila
Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:707:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:340:10)
    at new LoxoneAccessory (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:54:25)
    at LoxonePlatform.mapLoxoneItems (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:180:9)
    at LoxonePlatform.parseLoxoneConfig (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:85:10)
    at LoxonePlatform.LoxoneInit (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:56:10)
[28/04/2023, 19:33:54] [homebridge-loxone-proxy] Child bridge process ended
[28/04/2023, 19:33:54] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null`

**Comment by TommeDE** [comment]
hab das gefunden mit dem cache ... alles gelöscht und trotzdem ... 

`[28/04/2023, 19:40:37] [homebridge-loxone-proxy] [mapLoxoneItems][Item 108] Found item: [Keller] Rosa with type MoodSwitch
[28/04/2023, 19:40:37] [homebridge-loxone-proxy] [LoxoneAccesory] Item already mapped. Restoring accessory from cache: [Keller] Rosa
[28/04/2023, 19:40:38] [HomeConnect] Please authorise access to your appliances within 29 minutes 45 seconds using the associated Home Connect or SingleKey ID email address by visiting:
[28/04/2023, 19:40:38] [HomeConnect]     https://api.home-connect.com/security/oauth/device_verify?user_code=GSPY-TB2M
[28/04/2023, 19:40:38] [homebridge-loxone-proxy] [mapLoxoneItems][Item 109] Found item: [Keller] Lila with type MoodSwitch
[28/04/2023, 19:40:38] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Lila
Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:707:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:340:10)
    at new LoxoneAccessory (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:54:25)
    at LoxonePlatform.mapLoxoneItems (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:180:9)
    at LoxonePlatform.parseLoxoneConfig (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:85:10)
    at LoxonePlatform.LoxoneInit (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:56:10)
[28/04/2023, 19:40:38] [homebridge-loxone-proxy] Child bridge process ended
[28/04/2023, 19:40:38] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null
[28/04/2023, 19:40:45] [homebridge-loxone-proxy] Restarting Process...`

**Comment by rudyberends** [comment]
Dies liegt daran, dass sich noch über 150 Items im Homebridge-Cache befinden. Der Cache muss einmal gelöscht werden, damit es funktioniert. Wenn Sie homebridge-ui verwenden, können Sie den Cache leeren, indem Sie auf "Homebridge-Einstellung" gehen und "Geräte aus dem Cache entfernen" auswählen. Das Entfernen des Plugins, Neustarten und Neuinstallieren des Plugins könnte ebenfalls funktionieren.

**Comment by TommeDE** [comment]
kann jetzt noch versuchen das plugin neu zu installieren den cache für alle geräte mit neustart hab ich gemacht

**Comment by TommeDE** [comment]
[28/04/2023, 19:57:39] [homebridge-iobroker2] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 19:57:39] [homebridge-iobroker2] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 19:57:39] [homebridge-loxone-proxy] This plugin generated a warning from the characteristic 'Version': characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 19:57:39] [homebridge-loxone-proxy] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 45 exceeded maximum of 38. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 19:57:40] [homebridge-loxone-connect] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 19:57:48] [HomeConnect] Please authorise access to your appliances within 22 minutes 33 seconds using the associated Home Connect or SingleKey ID email address by visiting:
[28/04/2023, 19:57:48] [HomeConnect]     https://api.home-connect.com/security/oauth/device_verify?user_code=1X9M-Z202
[28/04

**Comment by rudyberends** [comment]
Ich werde diese Warnungen beheben, aber sie sollten das Plugin nicht daran hindern, zu funktionieren. Verhindert das Gegenstandslimit, dass die Brücke abstürzt?

**Comment by TommeDE** [comment]
alles was ich sehen kann im log hab ich geschickt jetzt kommen nur noch nachrichten der anderen plugins

**Comment by TommeDE** [comment]
nee jetzt nach neustart ist ne menge an geräten da sieht besser aus als bei dem anderen loxone adapter ... coooooool

**Comment by rudyberends** [comment]
Ist es möglich, für jedes Problem ein separates Problem zu erstellen, damit wir daran arbeiten und es separat testen können? Ich habe schon ein paar erstellt. Wenn das ursprüngliche Problem "149 Artikel" behoben ist, werde ich fortfahren, dieses Problem zu schließen.

**Comment by TommeDE** [comment]
leider nein nach der neuinstallation stand der schalter auf default

`
[28/04/2023, 20:43:07] [homebridge-loxone-proxy] [mapLoxoneItems][Item 107] Found item: [Keller] Rot with type MoodSwitch
[28/04/2023, 20:43:07] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Rot
[28/04/2023, 20:43:07] [homebridge-loxone-proxy] [mapLoxoneItems][Item 108] Found item: [Keller] Rosa with type MoodSwitch
[28/04/2023, 20:43:07] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Rosa
[28/04/2023, 20:43:08] [homebridge-loxone-proxy] [mapLoxoneItems][Item 109] Found item: [Keller] Lila with type MoodSwitch
[28/04/2023, 20:43:08] [homebridge-loxone-proxy] [LoxoneAccesory] Adding new accessory: [Keller] Lila
Error: Cannot Bridge more than 149 Accessories
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:683:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:707:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:384:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:340:10)
    at new LoxoneAccessory (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:54:25)
    at LoxonePlatform.mapLoxoneItems (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:180:9)
    at LoxonePlatform.parseLoxoneConfig (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:85:10)
    at LoxonePlatform.LoxoneInit (/usr/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:56:10)
[28/04/2023, 20:43:08] [homebridge-loxone-proxy] Child bridge process ended
[28/04/2023, 20:43:08] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null
[28/04/2023, 20:43:08] [homebridge-loxone-connect] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://homebridge.io/w/JtMGR for more info.
[28/04/2023, 20:43:08] [homebridge-iobroker2] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
`

**Comment by TommeDE** [comment]
hab nochmal den cache gelöscht und siehe da jetzt geht es ... vom feinsten!

**Comment by rudyberends** [comment]
fixed with commit d263e65
