### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by sooslaca** [rudyberends/homebridge-loxone-proxy#27]
Hello, very nice plugin indeed, thanks for your work!

A little feedback to make the plugin better:
```
[8/17/2023, 10:00:28 PM] TypeError: Cannot read properties of undefined (reading 'type')
     at LoxonePlatform.parseLoxoneConfig (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:63:39)
     at LoxonePlatform.LoxoneInit (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:34:10)
     at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:23:7)
```

Tracked problem back to this line: https://github.com/rudyberends/homebridge-loxone-proxy/blob/master/src/LoxonePlatform.ts#L63

Fix was easy: the UI element that I use was set 'Category' to 'do not use' in Loxone Config. I turned it to something else which is real category.

I'm not sure what is the use of `.type`, maybe just don't check it?

**Comment by rudyberends** [comment]
Thank you for your feedback.

https://github.com/rudyberends/homebridge-loxone-proxy/commit/f03c6867261313db0b8b5c1335afb7859e25dc06 Should fix your issues. It's in the latest beta. Perhaps you can test it?
