### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by MephistoJB** [rudyberends/homebridge-loxone-proxy#28]
After install the plugin cannot start.

[8/18/2023, 7:56:42 AM] [homebridge-loxone-proxy] Connected to Miniserver
TypeError: Cannot read properties of undefined (reading 'name')
    at LoxonePlatform.parseLoxoneConfig (/usr/local/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:62:42)
    at LoxonePlatform.LoxoneInit (/usr/local/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:34:10)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-proxy/src/LoxonePlatform.ts:23:7)
[8/18/2023, 7:56:43 AM] [homebridge-loxone-proxy] Child bridge process ended
[8/18/2023, 7:56:43 AM] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null
[8/18/2023, 7:56:45 AM] [homebridge-loxone-proxy] Restarting child bridge...

Any ideas how to fix this? Is this a known error?

**Comment by MephistoJB** [comment]
Maybe change line 60 of the LoxonePlatform.ts from:

```
for (const uuid in LoxoneItems) {
      const Item = LoxoneItems[uuid];
      Item.room = LoxoneRooms[Item.room].name;
      Item.cat = LoxoneCats[Item.cat].type;
    }
```

to

```
for (const uuid in LoxoneItems) {
try `{`
      const Item = LoxoneItems[uuid];
      Item.room = LoxoneRooms[Item.room].name;
      Item.cat = LoxoneCats[Item.cat].type;
} catch (error) {
        //console.log(error);
        this.log.debug(`[mapLoxoneItem] Skipping Unsupported Room or Category: ${item.room} with type ${item.cat}`);
      }
    }
```

This should make it more robust

**Comment by rudyberends** [comment]
Thank you for your feedback.

https://github.com/rudyberends/homebridge-loxone-proxy/commit/f03c6867261313db0b8b5c1335afb7859e25dc06 Should fix your issues. It's in the latest beta. Perhaps you can test it?

**Comment by MephistoJB** [comment]
thanks. Tested it. Seems to work right now. I will give you feedback when something changes
