### ISSUE TITLE
Cannot connect mini server

### ISSUE THREAD

**Issue by 40federico** [rudyberends/homebridge-loxone-proxy#44]
I think the last update of Loxone has broken something....
My installation has lock with video.
Previously running video fine. Now cannot connect to miniserver. The loxone version is: 14.3.8.28

This is the log of hb:
[9/25/2023, 9:15:45 AM] [homebridge-loxone-proxy] Child bridge process ended
[9/25/2023, 9:15:45 AM] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null
[9/25/2023, 9:15:52 AM] [homebridge-loxone-proxy] Restarting Process...
[9/25/2023, 9:15:53 AM] [homebridge-loxone-proxy] Launched child bridge with PID 3243
[9/25/2023, 9:15:53 AM] Registering platform 'homebridge-loxone-proxy.LoxonePlatform'
[9/25/2023, 9:15:53 AM] [homebridge-loxone-proxy] Loaded homebridge-loxone-proxy v1.4.0-beta.1 child bridge successfully
[9/25/2023, 9:15:53 AM] Loaded 34 cached accessories from cachedAccessories.0E92229A4E3B.
[9/25/2023, 9:15:53 AM] [homebridge-loxone-proxy] Trying to connect to Miniserver
[9/25/2023, 9:15:53 AM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-loxone-proxy) is running on port 46056.
[9/25/2023, 9:15:54 AM] [homebridge-loxone-proxy] Connected to Miniserver
TypeError: Cannot read properties of undefined (reading 'name')
    at IntercomV2.configureMotionSensor (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:28:42)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:16:12

**Comment by rudyberends** [comment]
could you post the intercom item from the structure file?

**Comment by 40federico** [comment]
Rechecked and works fine with homebridge-loxone-proxy v1.3.0

How I can obtain the intercom item you mention? sorry ... I am newbie...

**Comment by rudyberends** [comment]
You can download the structure file using a webbrowser by using the following url (change the ip to match your miniserver);
http://192.168.1.200/data/LoxAPP3.json. You will need your Loxone credentials.

There should be a "type: Intercomv2" entry. You might need an editor that formats the json to properly read it. 

If you could share this intercom entry it would be very helpful.

**Comment by 40federico** [comment]
> You can download the structure file using a webbrowser by using the following url (change the ip to match your miniserver); http://192.168.1.200/data/LoxAPP3.json. You will need your Loxone credentials.
> 
> There should be a "type: Intercomv2" entry. You might need an editor that formats the json to properly read it.
> 
> If you could share this intercom entry it would be very helpful.

Hi, sorry for the delay in respond.

Here is:



 
--
name | "Videoportero"
type | "IntercomV2"
uuidAction | "1aa9c378-016f-1e40-ffff61ca72c22e41"
room | "19560191-0091-3fe9-ffff61ca72c22e41"
cat | "1956018f-02a8-3c06-ffff61ca72c22e41"
defaultRating | 5
isFavorite | true
isSecured | false
restrictions | 0
details |  
jLockable | true
deviceType | 1
serialNr | "504F94E083D2"
deviceUuid | "1aa9ad35-034e-ea5b-ffff61ca72c22e41"
deviceName | "Videoportero"
optionsFramerate |  
0 |  
id | 5
name | "5 fps"
1 |  
id | 10
name | "10 fps"
2 |  
id | 15
name | "15 fps"
3 |  
id | 20
name | "20 fps"
optionsResolution |  
0 |  
id | 240
name | "240p"
1 |  
id | 360
name | "360p"
2 |  
id | 480
name | "480p"
3 |  
id | 720
name | "720p"
states |  
jLocked | "9aa9c378-016f-1e35-ffff05ad5e40eb62"
muted | "1aa9c378-016f-1e33-ffff05ad5e40eb62"
bell | "1aa9c378-016f-1e2c-ffff05ad5e40eb62"
version | "1aa9c378-016f-1e2b-ffff05ad5e40eb62"
address | "1aa9c378-016f-1e2d-ffff05ad5e40eb62"
answers | "1aa9c378-016f-1e2e-ffff05ad5e40eb62"
deviceState | "1aa9c378-016f-1e2f-ffff05ad5e40eb62"
videoSettingsIntern | "1aa9c378-016f-1e30-ffff05ad5e40eb62"
videoSettingsExtern | "1aa9c378-016f-1e31-ffff05ad5e40eb62"
subControls |  
1aa9c378-016f-1e40-ffff61ca72c22e41/1 |  
name | "Abrir puerta"
type | "Pushbutton"
uuidAction | "1aa9c378-016f-1e40-ffff61ca72c22e41/1"
defaultRating | 0
isFavorite | false
isSecured | false
restrictions | 0
states |  
active | "1aa9c378-016f-1e3c-ffff05ad5e40eb62"

**Comment by 40federico** [comment]
> Would you be able to install the latest beta version? (1.4.0.beta.2)
> 
> This will give you some additional debug output. Could you post these debug messages?

Here is:
TypeError: Cannot read properties of undefined (reading 'name')
    at IntercomV2.configureMotionSensor (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:36:42)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:16:12
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:52
    at Array.forEach (<anonymous>)
    at LoxoneHandler.registerListenerForUUID (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:32)
    at IntercomV2.configureCamera (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:10:33)
    at IntercomV2.configureServices (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:20:10)
    at IntercomV2.setupAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:45:10)
    at new LoxoneAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:31:10)
    at new Intercom (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:9:1)
[10/10/2023, 11:21:27 PM] [homebridge-loxone-proxy] Child bridge process ended
[10/10/2023, 11:21:27 PM] [homebridge-loxone-proxy] Process Ended. Code: 1, Signal: null
[10/10/2023, 11:21:34 PM] [homebridge-loxone-proxy] Restarting Process...
[10/10/2023, 11:21:34 PM] [homebridge-loxone-proxy] Launched child bridge with PID 14288
[10/10/2023, 11:21:35 PM] Registering platform 'homebridge-loxone-proxy.LoxonePlatform'
[10/10/2023, 11:21:35 PM] [homebridge-loxone-proxy] Loaded homebridge-loxone-proxy v1.4.0-beta.2 child bridge successfully
[10/10/2023, 11:21:35 PM] Loaded 35 cached accessories from cachedAccessories.0E92229A4E3B.
[10/10/2023, 11:21:35 PM] [homebridge-loxone-proxy] Trying to connect to Miniserver
[10/10/2023, 11:21:35 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-loxone-proxy) is running on port 46056.
[10/10/2023, 11:21:35 PM] [homebridge-loxone-proxy] Connected to Miniserver
!!! BEGIN DEBUG !!!
targetUuidPrefix: 1aa9ad35
intercomMotionUuid: 
undefined
!!! END DEBUG !!!

**Comment by rudyberends** [comment]
The latest release should fix your issue. There is a MotionSensor item available on these V2 intercoms. If you want to use it with this plugin you need to enable the "use in userinterface" option on this item in LoxoneConfig.

The latest release will just ignore it if it is not enabled.
