### ISSUE TITLE
Issue LoxoneIntercom

### ISSUE THREAD

**Issue by mauznk** [rudyberends/homebridge-loxone-proxy#46]
Hi, 
I have an Issue with the Plugin and the IntercomV2
Homebridge is restarting always because of an Charakteristik issue.

The Plugin is running on Version 1.4
```
[10/8/2023, 4:10:59 PM] [homebridge-loxone-proxy] Connected to Miniserver
TypeError: Cannot read properties of undefined (reading 'name')
    at IntercomV2.configureMotionSensor (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:28:42)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:16:12
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:52
    at Array.forEach (<anonymous>)
    at LoxoneHandler.registerListenerForUUID (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:32)
    at IntercomV2.configureCamera (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:10:33)
    at IntercomV2.configureServices (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:20:10)
    at IntercomV2.setupAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:45:10)
    at new LoxoneAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:31:10)
    at new Intercom (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:9:1)
```

**Comment by rudyberends** [comment]
Would you be able to install the latest beta version? (1.4.0.beta.2)

This will give you some additional debug output. Could you post these debug messages?

**Comment by mauznk** [comment]
For sure there you go.

```
[10/10/2023, 3:20:58 PM] [homebridge-loxone-proxy] Connected to Miniserver
!!! BEGIN DEBUG !!!
targetUuidPrefix: 17803381
intercomMotionUuid: 
undefined
!!! END DEBUG !!!
[10/10/2023, 3:20:59 PM] [homebridge-loxone-proxy] This plugin generated a warning from the characteristic 'Configured Name': Characteristic not in required or optional characteristic section for service Switch. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
TypeError: Cannot read properties of undefined (reading 'name')
    at IntercomV2.configureMotionSensor (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:36:42)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:16:12
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:52
    at Array.forEach (<anonymous>)
    at LoxoneHandler.registerListenerForUUID (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:181:32)
    at IntercomV2.configureCamera (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:10:33)
    at IntercomV2.configureServices (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:20:10)
    at IntercomV2.setupAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:45:10)
    at new LoxoneAccessory (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:31:10)
    at new Intercom (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:9:1)
```



I also checked my json from Loxone if the device UUID is matching.
The json and the Debug output with "targetUuidPrefix" is correct.

**Comment by rudyberends** [comment]
The latest release should fix your issue. There is a MotionSensor item available on these V2 intercoms. If you want to use it with this plugin you need to enable the "use in userinterface" option on this item in LoxoneConfig.

The latest release will just ignore it if it is not enabled.
