### ISSUE TITLE
Add Support for LichtControllerV2 Smart Actor for  Sport RGBW and Ceiling Light RGBW

### ISSUE THREAD

**Issue by geppertm86** [rudyberends/homebridge-loxone-proxy#67]
Hi,
Getting the Message that HSV and Color Temp are a ToDo

todo: colortemp(100,4600)
todo: colortemp(19,4600)
todo: colortemp(0,4600)
todo: colortemp(49,4600)
todo: colortemp(79,4600)
todo: colortemp(100,4600)
todo: colortemp(60,4600)
todo: colortemp(35,4600)
todo: colortemp(23,4600)
todo: colortemp(14,4600)
todo: colortemp(9,4600)
todo: colortemp(0,4600)
todo: colorhsv(24,96,77)
todo: colorhsv(337,94,50)
todo: colorhsv(337,94,0)
todo: colorhsv(24,96,77)

Behavior is also if Spots or Ceiling light is turned on via Loxone, it is not visible in Home / Homebridge.
After turned on via Home, Device can't be turned off.

**Comment by geppertm86** [comment]
I played a little bit , seems the issue is coming only when turning the device from off to on.
When you Edit the Color / Temperature and Brightness is is working as expected until you turn it off.
Guess the issue is in the State.Brightness  =  0 in the constructor ?

**Comment by rudyberends** [comment]
I do not have RGB spots myself, so I am unable to test this. The latest beta contains code to handle updates for this item from the Loxone side.

Could you test the latest beta version and let me know If it works for you?

**Comment by geppertm86** [comment]
Beta is giving this error, either when turning on/off via Home and on change on Loxone Side

TypeError: Cannot read properties of undefined (reading 'minCtLoxone')
    at loxoneToHomekitColorTemperature (/homebridge/node_modules/homebridge-loxone-proxy/src/homekit/services/ColorLightBulb.ts:212:35)
    at processTemp (/homebridge/node_modules/homebridge-loxone-proxy/src/homekit/services/ColorLightBulb.ts:86:39)
    at ColorLightBulb.updateService (/homebridge/node_modules/homebridge-loxone-proxy/src/homekit/services/ColorLightBulb.ts:96:5)
    at ColorPickerV2.eval (eval at LoxoneAccessory.callBack (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:102:31), <anonymous>:3:36)
    at ColorPickerV2.LoxoneAccessory.callBack (/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:103:23)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:56
    at Array.forEach (<anonymous>)
    at handleAnyEvent (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:36)
    at Object.socketOnEventReceived (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:99:17)
    at WebSocket._handleBinaryEvent (/homebridge/node_modules/homebridge-loxone-proxy/node_modules/lxcommunicator/modules/WebSocket.js:934:78)

**Comment by rudyberends** [comment]
could you try again using the latest beta?

**Comment by geppertm86** [comment]
Congratulations, working!

I will do some more testing

**Comment by rudyberends** [comment]
Thank you for testing. Please let me know if you have any more issues with it. 
When it is working as expected for you, i will push the changes to the normal release.
