### ISSUE TITLE
Plugin Crash after Config deployment to Miniserver

### ISSUE THREAD

**Issue by geppertm86** [rudyberends/homebridge-loxone-proxy#80]
Hi,

When deploying a new Config to the Miniserver the Plugin crashes after the reconnect... seems to be an issue with the Camera provide by the Intercom Gen 2

[1/23/2024, 9:29:13 AM] [LoxonePlatform] Connected to Miniserver
Miniserver out of service!
[1/23/2024, 9:36:47 AM] [LoxonePlatform] Socket closed 2008
[1/23/2024, 9:36:47 AM] [LoxonePlatform] Reconnecting in 10 seconds...
[1/23/2024, 9:36:57 AM] [LoxonePlatform] Trying to connect to Miniserver
[1/23/2024, 9:36:57 AM] [LoxonePlatform] Connected to Miniserver
Error: A Controller with the type/id 'camera' was already added to the accessory Sprechanlage
    at Accessory.configureController (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:847:13)
    at PlatformAccessory.configureController (/homebridge/node_modules/homebridge/src/platformAccessory.ts:148:34)
    at Camera.setupService (/homebridge/node_modules/homebridge-loxone-proxy/src/homekit/services/Camera.ts:22:20)
    at new Camera (/homebridge/node_modules/homebridge-loxone-proxy/src/homekit/services/Camera.ts:13:10)
    at IntercomV2.setupCamera (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Intercom.ts:54:5)
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/IntercomV2.ts:13:12
    at /homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:56
    at Array.forEach (<anonymous>)
    at handleAnyEvent (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:36)
    at Object.socketOnEventReceived (/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:99:17)

**Comment by rudyberends** [comment]
It should be fixed in [v1.9.0-beta.7](https://github.com/rudyberends/homebridge-loxone-proxy/releases/tag/v1.9.0-beta.7)

Could you test and let me know if it resolves the issue for you?

**Comment by geppertm86** [comment]
Testet it several times.
Fix is working!
Congrats!
