### ISSUE TITLE
Errors with Radio buttons

### ISSUE THREAD

**Issue by 350d** [rudyberends/homebridge-loxone-proxy#84]
I have these warnings in HB console until `Radio` as exception added to config:

```
[01/02/2024, 23:42:34] [homebridge-loxone-proxy] This plugin generated a warning from the characteristic 'Configured Name': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
...
...
[01/02/2024, 23:42:34] [homebridge-loxone-proxy] This plugin generated a warning from the characteristic 'Configured Name': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[01/02/2024, 23:42:34] [LoxonePlatform] Connected to Miniserver
SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at Radio.callBackHandler (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/items/Radio.ts:42:29)
    at Radio.LoxoneAccessory.callBack (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/LoxoneAccessory.ts:95:12)
    at /var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:56
    at Array.forEach (<anonymous>)
    at handleAnyEvent (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:69:36)
    at Object.socketOnEventReceived (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/src/loxone/LoxoneHandler.ts:96:17)
    at WebSocket._handleBinaryEvent (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/node_modules/lxcommunicator/modules/WebSocket.js:934:78)
    at WebSocket._binaryMessageHandler (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/node_modules/lxcommunicator/modules/WebSocket.js:773:26)
    at W3CWebSocket.onmessage (/var/lib/homebridge/node_modules/homebridge-loxone-proxy/node_modules/lxcommunicator/vendor/WebSocketWrapper.js:107:62)
[01/02/2024, 23:42:35]
```

**Comment by rudyberends** [comment]
can you turn on debug logging in homebridge and reproduce the error?

**Comment by 350d** [comment]
I've tried to enable debug mode and 'Remove All Cached Accessories' but now I don't have these error messages in logs...

**Comment by rudyberends** [comment]
Are you still having issues with it?

**Comment by rudyberends** [comment]
please reopen if you are still having issues
